Enabled running pre-commit hook in ignore-errors mode

diff --git a/bin/pre-commit b/bin/pre-commit
--- a/bin/pre-commit
+++ b/bin/pre-commit
@@ -2,7 +2,6 @@
 
 PROJECT=$(git rev-parse --show-toplevel)
 STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
-
 # Determine if a file list is passed
 if [ "$#" -eq 1 ]
 then
@@ -14,13 +13,18 @@ then
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
+if [ -n "$STATIC_ANALYSIS_IGNORE_ERRORS" ]
+then
+    echo "\nNote: You're using IGNORE_ERRORS mode - PHP errors will be detected, but will not block the commit.\n"
+    sleep 3s
+fi
 echo "Checking PHP Lint..."
 for FILE in $SFILES
 do
     php -l -d display_errors=0 $PROJECT/$FILE
     if [ $? != 0 ]
     then
-        echo "Fix the error before commit."
+        echo "Fix the PHP errors before commit."
         exit 1
     fi
     FILES="$FILES $PROJECT/$FILE"
@@ -32,8 +36,14 @@ then
     ./bin/phpcs --standard=PSR2 --encoding=utf-8 -n -p $FILES
     if [ $? != 0 ]
     then
-        echo "Fix the Code Sniffer errors before commit."
-        exit 1
+        if [ -n "$STATIC_ANALYSIS_IGNORE_ERRORS" ]
+        then
+            echo "Code Sniffer found some errors."
+        else
+            echo "Fix the Code Sniffer errors before commit."
+            exit 1
+        fi
+        
     fi
 fi
 
@@ -43,8 +53,14 @@ do
     ./bin/phpmd $PROJECT/$FILE text cleancode,codesize,controversial,design,naming,unusedcode
     if [ $? != 0 ]
     then
-        echo "Fix the PHP Mess Detector errors before commit."
-        exit 1
+        if [ -n "$STATIC_ANALYSIS_IGNORE_ERRORS" ]
+        then
+            echo "PHP Mess Detector found some errors."
+        else
+            echo "Fix the PHP Mess Detector errors before commit."
+            exit 1    
+        fi
+        
     fi
 done
 
